import React from 'react';
import Cloud from '../Cloud/Cloud';
import './CloudContainer.css';

const CloudContainer: React.FC = () => {
    return (
        <section className="cloud-container">
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
            <Cloud />
        </section>
    );
};

export default CloudContainer;
